### ISSUE TITLE
Buying other items than the selected

### ISSUE THREAD

**Issue by Maldark** [Metric/AnSAddons#1]
Hi,

First of all, thanks for the addon - I've just started using it and I am very happy with the speed.

That being said, I was just "sniping" some Tidespray Linen posted at a favorable price, when it suddenly bought a Talasite. It's worth mentioning that the only categories selected were BFA Ore, BFA Cloth, and BFA Leather.

Here's a screenshot of the chat: https://i.imgur.com/hr8v2OG.png

**Comment by Metric** [comment]
Yes, this is a known issue, but there isn’t much I can do about it. Since,
it is mainly server related.

As someone posted earlier in the reddit thread, where they sent a purchase
request but then received a new query results with what appeared to be
another set of the same item. However, his bid was finalized after this and
he then bid on the new item he saw. But that item had already been
purchased by him and thus it purchased another item at the same index.

My point is, it seems the server actually confirms based on the index sent
from the client, rather than an actual unique ID provided by their auc ID
in their database.

**Comment by Metric** [comment]
It seems the pull request by tieonlinux, does indeed fix this issue. Will be pushing out a new build tonight. 

I can definitely confirm, that it does fix the issue where if you buy something, and the new query is pulled, but says the item is still there. It will no longer buy weird results, if you try and buy the item again.

**Comment by Maldark** [comment]
That's great news! Thanks for the quick support!
