### ISSUE TITLE
Sniper doesnt  show any items if we have filter group with only base item ID idded.

### ISSUE THREAD

**Issue by FoiFoish** [Metric/AnSAddons#11]
In new version sniper doesnt  show any items if i try to search items that can have bonus id's. So instead a group with base id's there is necessary to create group with all possible variations of item.
Thank you for 8.3 update :)

**Comment by Metric** [comment]
I forgot to include in the readme, but I did post this info on reddit.
Please up your max percent higher than necessary or create a custom filter
to override the max percent. This is required, due to how it can only use
the base id when checking the browse group for filtering price in tsm and
tuj. If the base id group isn’t considered due to max percent then it will
never scan the other higher ilevel / bonus ids in the final scan. As it
skips over the browse groups based on that base id.

**Comment by FoiFoish** [comment]
Yes, i understand that. Here is my example: a group with eternal palace cloak (i:168602) with filter ppu lt 500000g, when i click start there is "Gathering auctions" scan but there is no any result. But if I add available item with exact bonus (i:168602::4:1517:1808:4786:4800 for example), with exact filter (ppu lt 500000g) there is will be a result.

**Comment by Metric** [comment]
That is correct the final scan in a group is an exact scan on item id +
bonus ids. Thus, you will need to include all bonus ids with the item id to
have it show up in the final scan. The group scan is based on base id only.
You do not need to include the base id in a filter if you provide the id +
bonus ids. This only applies to equipment based scans.

The bonus ids should be included in the sort order of low to high like in
muffins list.

Battle pet scan requires the pet species id + pet level + pet breed quality.

I will need to add this information to the readme + curseforge and add in
an option to disable exact item id bonus / pet level / pet breed matches on
a filter.

**Comment by FoiFoish** [comment]
> add in
an option to disable exact item id bonus / pet level / pet breed matches on
a filter.

That would be an ideal implementation. Thank you.
